version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=lpedrozo
      - POSTGRES_PASSWORD=r3b3c4
    ports:
      - 5232:5232
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

